import type { ScenarioDef } from '../types/story';

export const SCENARIOS: ScenarioDef[] = [
  {
    id: 'isekai',
    title: 'Isekai Transit',
    sub: 'A stranger in a world of swords and sorcery',
    tag: 'Isekai',
    setting: 'Kingdom of Aetherholm — feudal high-magic realm, cobblestone towns, guilds, airships, demon invasion imminent on the eastern border.',
    char: 'Lyra — half-elf bard guide, has shepherded otherworlders before, knows too much.',
    hook: 'You wake in a wheat field at dawn. A girl in travel leathers is staring at you.',
    player: 'A modern human, no magic, oddly immune to mind-control — very valuable.',
  },
  {
    id: 'dungeon',
    title: 'The Forgotten Dungeon',
    sub: 'Ruin, treasure, and things that should stay buried',
    tag: 'Dungeon',
    setting: 'Sprawling underground ruin beneath Thornwood Forest. Crumbling corridors, phosphorescent moss, ancient magical constructs.',
    char: 'Arix — stone golem guardian, three hundred years old, sarcastic, knows every trap.',
    hook: 'You fall through a rotting floor into a chamber sealed for three centuries. A torch ignites on its own.',
    player: 'Adventurer seeking the Orb of Echoes. Short sword, lockpicks, half-used spell scroll.',
  },
  {
    id: 'cyber',
    title: 'Neon Exodus',
    sub: 'Rain-slicked megacity, corporate wars, black-market chrome',
    tag: 'Cyberpunk',
    setting: 'Neo-Hakodate, 2097. Six megacorps carved the city. Between them: the Sprawl — 40 floors of unregulated chaos.',
    char: 'Spectre — disembodied AI in your neural implant. Amoral, information-addicted.',
    hook: 'Your contact is dead. Their last encrypted message has coordinates and one word: EXODUS.',
    player: 'Mid-tier fixer, cracked cyberleg, reputation for discretion, debt to the wrong corp.',
  },
  {
    id: 'spirit',
    title: 'Spirit Realm Negotiator',
    sub: 'Yokai courts, shrine bargains, the politics of the unseen',
    tag: 'Mythology',
    setting: 'Feudal Japan in the Spirit Mirror — parallel realm, shrines are embassies, every deity has a seat.',
    char: 'Kitsune-no-Nana — seven-tailed fox spirit, ancient, mercurial, bound to you by childhood contract.',
    hook: 'Your childhood shrine has gone dark. The rice offerings rot overnight. All nine factions blame each other.',
    player: 'Travelling monk with rare ability to see through spirit-illusions. Indispensable — and a target.',
  },
  {
    id: 'romance',
    title: "The Noble's Gambit",
    sub: 'Intrigue, poison, and a throne no one should want',
    tag: 'Romance',
    setting: 'Imperial Court of Velundra — masquerades, poisoned wine, three factions each believe the throne is theirs.',
    char: 'Lord Caelion — third son of a rival house, dangerously charming, hiding a secret.',
    hook: 'An invitation arrives sealed in black wax. The masquerade ball is tonight.',
    player: "Merchant's child given a hollow title and tasked with unmasking a traitor.",
  },
  {
    id: 'custom',
    title: 'Custom World',
    sub: 'Start from a blank page',
    tag: 'Custom',
    setting: '',
    char: '',
    hook: '',
    player: '',
  },
];
